version: '3.7'

services:
  tv-backend:
    container_name: tv-backend
    image: tv-backend:0.0.1
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 8115:3000
    environment:
      MONGO: ${MONGO}
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network: